### Un usuario crea un entrenamiento o en otras palabras asigna una rutina a un usuario. (Un Cliente lo crea y se lo asigna a si mismo o un Profesor lo crea y se lo asigna a un cliente)
POST http://localhost:3000/entrenamiento
Content-Type: application/json

{
    "rutina_id": 6,  
    "usuario_id" : 4,
    "fecha":"16/11/2024"
}

### Obtener un entrenamiento de un usuario en particular de una fecha en particular. (Ejemplo: usuario_id=4 and fecha=2024-11-14)
GET http://localhost:3000/entrenamiento/4/2024-11-16


### Obtener los entrenamientos de un usuario en particular en un mes en particular. (Ejemplo: usuario_id=4 and fecha=11-2024)
GET http://localhost:3000/entrenamiento/4/11/2024


### Modifica un entrenamiento en particular
PATCH http://localhost:3000/entrenamiento/30
Content-Type: application/json

{
    "rutina_id": 7,  
    "usuario_id" : 4,
    "fecha":"17/11/2024"
}


### Elimina un entrenamiento en particular
DELETE http://localhost:3000/entrenamiento/4/17/11/2024


### Recupera todas las rutinas que fueron asignadas en algun entrenamiento de un usuario
GET http://localhost:3000/entrenamiento/4


