### Recuperar todos los Gimnasios.
GET http://localhost:3000/gimnasios

### Recuperar un Gimnasio por id.
GET http://localhost:3000/gimnasios/2


### Crear un Gimnasio
POST http://localhost:3000/gimnasios
Content-Type: application/json

{
    "nombre" : "Megatlon",
    "direccion" : "Cam. Parque Centenario 4000",
    "ciudad" : "La Plata",
    "telefono" : "2216492814",
    "precio_membresia" :30000,
    "imagen_url" : "https://lh3.googleusercontent.com/p/AF1QipOldGVtceC5P5QlURGtiz84v8FHfhcVNuvnxeRR=s1360-w1360-h1020"
  }

### Actualizar un Gimnasio
PUT http://localhost:3000/gimnasios/2
Content-Type: application/json

{
    "nombre" : "Box Cntral",
    "direccion" : "13 entre 55 y 56",
    "ciudad" : "La Plata",
    "telefono" : "2216492914",
    "precio_membresia" :20000,
    "imagen_url" : "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQXgCo51vMyCSPeLVznzlSQEF-ZA4Cw4NsOHg&s"
  }


### Actualizar un Gimnasio parcialmente (solo algunas propiedades)
PATCH http://localhost:3000/gimnasios/4
Content-Type: application/json

{   "nombre": "Skay Gym"
    
}

### Eliminar un gimnasio.
DELETE http://localhost:3000/gimnasios/2