### Recuperar todos los Gimnasios.
GET http://localhost:3000/gimnasios

### Recuperar un Gimnasio por id.
GET http://localhost:3000/gimnasios/2

### Recuperar todos los gimnasios de la ciudad de La Plata.
GET http://localhost:3000/movies?ciudad=La%Plata

### Crear un Gimnasio
POST http://localhost:3000/gimnasios
Content-Type: application/json

{
    "nombre" : "Prueba Validacion",
    "direccion" : "13 entre 55 y 56",
    "ciudad" : "La Plata",
    "telefono" : "2216492914",
    "precio_membresia" :20000,
    "imagen_url" : "https://lh3.googleusercontent.com/p/AF1QipMeXhFOh6-J6FgGJ-dRbkVqHzOTVkQwZRT9HlbI=s1360-w1360-h1020"
  }

### Actualizar un Gimnasio
PUT http://localhost:3000/gimnasios/2
Content-Type: application/json

{
    "nombre" : "Box Cntral",
    "direccion" : "13 entre 55 y 56",
    "ciudad" : "La Plata",
    "telefono" : "2216492914",
    "precio_membresia" :20000,
    "imagen_url" : "https://lh3.googleusercontent.com/p/AF1QipMeXhFOh6-J6FgGJ-dRbkVqHzOTVkQwZRT9HlbI=s1360-w1360-h1020"
  }


### Actualizar un Gimnasio parcialmente (solo algunas propiedades)
PATCH http://localhost:3000/gimnasios/2
Content-Type: application/json

{
    "nombre" : "Prueba Parcial"
    
}

### Eliminar un gimnasio.
DELETE http://localhost:3000/gimnasios/2