### Incribir Usuario a un Gimnasio
POST http://localhost:3000/miembro
Content-Type: application/json

{
    "usuario_id" : "2",
    "gimnasio_id": "1",
    "fecha_inicio":"2024-10-28T12:00:00Z",
    "fecha_fin":"2024-11-28T12:00:00Z",
    "precio": 25000,
    "estado_membresia_id": 1
}

### Obtener los gimnasios a los que está incripto un usuario.
GET http://localhost:3000/miembro/gimnasios/2

### Obtener los gimnasios disponibles para un usuario. (A los que no esta inscripto)
GET http://localhost:3000/miembro/gimnasios/disponibles/2
